# Generated by Django 4.1.1 on 2022-10-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_location_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="google_place_id",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
