# Generated by Django 4.1.1 on 2022-10-08 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
