# Generated by Django 4.1.1 on 2022-10-08 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_location_active_review_email_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="min_rating",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
