# Generated by Django 4.1.1 on 2022-11-08 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_location_min_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="min_rating",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
