# Save to /etc/nginx/sites-available/
# sudo ln -s /etc/nginx/sites-available/levreview.nginx.conf /etc/nginx/sites-enabled
# sudo nginx -t
# sudo systemctl restart nginx

server {
    server_name levreview.com www.levreview.com;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        root /home/rasulkireev/levreview;
    }

    location /media {
        root /home/rasulkireev/levreview;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/levreview.gunicorn.sock;
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/levreview.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/levreview.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
    if ($host = www.levreview.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = levreview.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name levreview.com www.levreview.com;
    listen 80;
    return 404; # managed by Certbot




}
