# This is a basic workflow to help you get started with Actions

name: Prod Deploy

on:
  push:
    branches:
      main

env:
  PROJECT_DIR: /home/rasulkireev/levreview
  DO_PASSWORD: ${{ secrets.DO_PASSWORD }}
  SUDO_PREFIX: "echo ${{ secrets.DO_PASSWORD }} | sudo -S"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Latest Commit
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: PROJECT_DIR
          script: |
            cd $PROJECT_DIR
            git fetch --all
            git reset --hard origin/main

      - name: Install Conf Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: PROJECT_DIR,DO_PASSWORD,SUDO_PREFIX
          script: |
            $SUDO_PREFIX cp $PROJECT_DIR/deployment/levreview.gunicorn.socket /etc/systemd/system/levreview.gunicorn.socket
            $SUDO_PREFIX cp $PROJECT_DIR/deployment/levreview.gunicorn.service /etc/systemd/system/levreview.gunicorn.service
            $SUDO_PREFIX cp $PROJECT_DIR/deployment/levreview.nginx.conf /etc/nginx/sites-available/levreview.nginx.conf
            $SUDO_PREFIX ln -s /etc/nginx/sites-available/levreview.nginx.conf /etc/nginx/sites-enabled/levreview.nginx.conf

      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: PROJECT_DIR,SUDO_PREFIX
          script: |
            cd $PROJECT_DIR
            source ./venv/bin/activate
            pip install -r requirements.txt
            npm install

      - name: Build Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: PROJECT_DIR
          script: |
            cd $PROJECT_DIR
            npm run build
            source ./venv/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput
            python manage.py djstripe_sync_models

      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: DO_PASSWORD,SUDO_PREFIX
          script: |
            $SUDO_PREFIX systemctl restart levreview.gunicorn
            $SUDO_PREFIX systemctl restart nginx
