# This is a basic workflow to help you get started with Actions

name: Prod Deploy

on:
  push:
    branches:
      main

env:
  PROJECT_DIR: /home/rasulkireev/levreview
  DO_PASSWORD: ${{ secrets.DO_PASSWORD }}

jobs:
  prepare:
    name: Prepare Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Latest Commit
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: PROJECT_DIR
          script: |
            cd $PROJECT_DIR
            git fetch --all
            git reset --hard origin/main

      - name: Install Conf Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script_stop: true
          envs: PROJECT_DIR,DO_PASSWORD
          script: |
            cp $PROJECT_DIR/deployment/levreview.gunicorn.socket /etc/systemd/system/
            cp $PROJECT_DIR/deployment/levreview.gunicorn.service /etc/systemd/system/

            echo "$DO_PASSWORD" | sudo systemctl start levreview.gunicorn.socket
            sudo systemctl enable levreview.gunicorn.socket
            sudo systemctl status levreview.gunicorn.socket

            file /run/levreview.gunicorn.sock
            sudo journalctl -u levreview.gunicorn.socket
            sudo systemctl status gunicorn

            cp $PROJECT_DIR/deployment/levreview.nginx.conf /etc/nginx/sites-available/
            sudo ln -s /etc/nginx/sites-available/levreview.nginx.conf /etc/nginx/sites-enabled
            sudo nginx -t
            sudo systemctl restart nginx
